# Generated by Django 4.2.2 on 2023-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygone',
            old_name='polygone',
            new_name='coordonnees',
        ),
        migrations.AlterField(
            model_name='polygone',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
